const Biography=[
    {
        "id":1,
        "name":"A Beautiful Mind ",
        "image":"https://previews.dropbox.com/p/thumb/ABqezDGzaiEdhXzV3T6dRrLHn1HFMi6Iz-hwrQUghgaDpLScGJt7eihUvwyWBui5WAmsYBekqTu3DAW6h9ZTtQMC-TlUOudi4gv9GrLvYXT03o4oRZZ6gmh0yA9S4_ydkEtKWi-kBHVbLI-32WZequ1EZsFr6bVMOx-uOvDXQp5inO7ptHHXF_bnhkHqK74q7OjyhNDNsFV6fJ8RB5in0jXq8XFgIZ-YDfxOoR47mbM7sincmBVFptdFcpoX1xq6WZ4eLDWk8dDAQYXBKcrkTnkuTm5tMbiLQsq0JwdhPWbCb1YHWqAHi1lRftpFl86QHnp7YqMcHkfF_bp96_hsV128W9AcyS_kjJtW1W4gnTyhwrswdhpJdK_bZIrrewP0W2w/p.jpeg",
        "des":"A Beautiful Mind is Sylvia Nasar's award-winning biography about the mystery of the human mind, the triumph over incredible adversity, and the healing power of love. At the age of thirty-one, John Nash, mathematical genius, suffered a devastating breakdown and was diagnosed with schizophrenia. Yet after decades of leading a ghost-like existence, he was to re-emerge to win a Nobel Prize and world acclaim. A Beautiful Mind has inspired the Oscar-winning film directed by Ron Howard and featuring Russell Crowe in the lead role of John Nash",
        "link":"https://online.fliphtml5.com/jappq/smfq/"
    },
    {
        "id":2,
        "name":"A Lincoln A Biography",
        "image":"https://previews.dropbox.com/p/thumb/ABqtCmJrkfFx6cBHFi1kqAZqVZo7OFpPByQiPy5ridmGm-emyoNBautbMFIb8mA3Muc7oDOzqa6-CUk1XDczv6g-dgN64DgNduVHD3x1vgzqvD33OC2QS_yR-456baoMqAbHyJBhnM7yCjNNMwgMBt52QCLXhmzrd9iCMy54KXtzlXHRP9gHCYa18pl1cWhJPB0cNDGsGkWwp5MBWTAKi1JrQsnMAAvyySNS7BNVF16OgGK-sVpqSuy9jaKqmfx1dC0ebpwx1vy5WUaQkTGEw5fA2rAWyriTTuqBYgVjpPxxSWAD_O73SYO0vZlkvYj0U4za6fq7L6QAeJHudRA0FyzyuEjz0vY3XBk3A2fmd7avuzeTp9PDY1qRV_gHUHiLwJo/p.jpeg",
        "des":"Everyone wants to define the man who signed his name “A. Lincoln.” In his lifetime and ever since, friend and foe have taken it upon themselves to characterize Lincoln according to their own label or libel. In this magnificent book, Ronald C. White, Jr., offers a fresh and compelling definition of Lincoln as a man of integrity–what today’s commentators would call “authenticity”–whose moral compass holds the key to understanding his life. Through meticulous research of the newly completed Lincoln Legal Papers, as well as of recently discovered letters and photographs, White provides a portrait of Lincoln’s personal, political, and moral evolution. White shows us Lincoln as a man who would leave a trail of thoughts in his wake, jotting ideas on scraps of paper and filing them in his top hat or the bottom drawer of his desk; a country lawyer who asked questions in order to figure out his own thinking on an issue, as much as to argue the case; a hands-on commander in chief who, as soldiers and sailors watched in amazement, commandeered a boat and ordered an attack on Confederate shore batteries at the tip of the Virginia peninsula; a man who struggled with the immorality of slavery and as president acted publicly and privately to outlaw it forever; and finally, a president involved in a religious odyssey who wrote, for his own eyes only, a profound meditation on “the will of God” in the Civil War that would become the basis of his finest address. Most enlightening, the Abraham Lincoln who comes into focus in this stellar narrative is a person of intellectual curiosity, comfortable with ambiguity, unafraid to “think anew and act anew.”A transcendent, sweeping, passionately written biography that greatly expands our knowledge and understanding of its subject, A. Lincoln will engage a whole new generation of Americans. It is poised to shed a profound light on our greatest president just as America commemorates the bicentennial of his birth.",
        "link":"https://online.fliphtml5.com/jappq/wris/"
    },
    {
        "id":3,
        "name":"Alan Turing: The Enigma: The Book That Inspired the Film The Imitation Game",
        "image":"https://previews.dropbox.com/p/thumb/ABqyX8RHMK5dkgDF68zFCW9ZTjHtnd_DllYyPNibHEEfBaK0hqaVV15PjH65o9BM7v3Oj7vMfBa2FPOt2Whek7uL35OZT3wDXd7DdbwUFg-8rIygOcTPBUq4QmvhR7xBNuQdmABLA0rt7bcw_urq7xcxde1aIULOm9SbULnQBtFJpGM6_3nClJNkSzhj5CAS_TMw1Z73NOM86-ilR5la_hNNP7MEpXreYbIwJ-a_Aix7pO3W1O2Jzd3qKpfSOMODp0nS0hxfjG9orUOrvLbzjx2b6aSU7CkCs8WFfdSXsE662lybI0-CHie702lbRDVXEiFMDN78B8kTS3vsRwA5lxK9pDs74YLefk_rCB3vzkABI807dmKF61keXJw4apnmNIA/p.jpeg",
        "des":"A NEW YORK TIMES BESTSELLERThe official book behind the Academy Award-winning film The Imitation Game, starring Benedict Cumberbatch and Keira KnightleyIt is only a slight exaggeration to say that the British mathematician Alan Turing (1912-1954) saved the Allies from the Nazis, invented the computer and artificial intelligence, and anticipated gay liberation by decades--all before his suicide at age forty-one. This New York Timesbestselling biography of the founder of computer science, with a new preface by the author that addresses Turing's royal pardon in 2013, is the definitive account of an extraordinary mind and life.Capturing both the inner and outer drama of Turings life, Andrew Hodges tells how Turings revolutionary idea of 1936--the concept of a universal machine--laid the foundation for the modern computer and how Turing brought the idea to practical realization in 1945 with his electronic design. The book also tells how this work was directly related to Turings leading role in breaking the German Enigma ciphers during World War II, a scientific triumph that was critical to Allied victory in the Atlantic. At the same time, this is the tragic account of a man who, despite his wartime service, was eventually arrested, stripped of his security clearance, and forced to undergo a humiliating treatment program--all for trying to live honestly in a society that defined homosexuality as a crime.The inspiration for a major motion picture starring Benedict Cumberbatch and Keira Knightley, Alan Turing: The Enigma is a gripping story of mathematics, computers, cryptography, and homosexual persecution.",
        "link":"https://online.fliphtml5.com/jappq/dqgq/"
    },
    {
        "id":4,
        "name":"Alexander Hamilton",
        "image":"https://previews.dropbox.com/p/thumb/ABqAA735HYHC_1ZH3gPVh52MV0m8ZBOfgLKCAym4ddHpyh6_2qqP44ijdldQawJknwKaoaqY2Dv-AJHE1bso92T07gCFXCjDqztBZO9tlECCkVIGDRyUkvn-dvNRxUjbmXbQDQ3tF1XwSlGqPnOGEXotkjcz0xuy8SGa-VSPJ_P8tEQDUBrPYTq9w_9x7_0zGa6RVn3IuADbbKN7Fk1jCN2atw2XTpMhM5oL90-FDmniMmsFlbv_SHbf_gnhN2VoP6ezOroo-AhNYYwipha2gSQnofX4-Ub7ObfTEriLTNS6NDrwPxXUHzZSfMIc_6zxq5kM8yhiNK8pFEVAPvaMfkqoJ5zR6ESIOyY-LZK5yuHjmYrkmWFxtLSoRFEIVYo8cC0/p.jpeg",
        "des":"Are you a fan of Lin-Manuel Miranda’s Hamilton? If so, this biography by Pulitzer Prize-winning author Ron Chernow is a must-read. The book—jokingly referred to as “Hamiltome” because of its hefty size—chronicles the life of this Founding Father. It starts with Hamilton’s humble beginnings as an orphan, then winds its way through his service as a staunch patriot in George Washington’s army. It also showcases Hamilton’s meteoric rise to become the first Treasury Secretary of the United States before ending with his death, which came at the hands of a duel with Aaron Burr.",
        "link":"https://online.fliphtml5.com/jappq/fvzj/"
    },
    {
        "id":5,
        "name":"Einstein: His Life and Universe",
        "image":"https://previews.dropbox.com/p/thumb/ABr9CB7DwJbLUasdB_pj3qj4EFTpwXWDFOriBkIcRe8VefBKJUUpMd8OBxQRaVYskH8eGNuXJEAfFIIsBhPAGHtFNNGAkMrb5y4OPpuwKhodi3AEJ7LJIn_26W2TpSZThc-eY6FIsZj8x7SvQc-WZcGDt3e2mLK_x37HedadQ5qw8Eeq1cADeVDdKBVPIXtV-9r9M39e8dgvbv2YgNtu1zBNbE0Xr2PitG-lCdI54KFIM24uBAavh8g2EjwDEX804JYVuur3UXUcQrFeoOltbRP1nxsSEH7ekPXL7T3h8duILTWLPXV8LWiE2bnqiatVDxIsYio19tG65KOcBciImIq_66Taas6SVm5oUPok0TmKntFwofmtiUzYQ777CfywL8w/p.jpeg",
        "des":"Yes, Albert Einstein was a genius, and plenty has already been written about the physicist’s Nobel Prize-winning scientific discoveries. Where this book differs, however, is in its examination of the aspects of Einstein’s life that made him human and relatable. Because of Einstein’s “sassy attitude,” for example, he was unable to find a job after graduating from Swiss Federal Polytechnic in Zurich, where he studied physics. One of the best biographies on Einstein, the book discusses how Einstein’s insolent personality served as the impetus for his groundbreaking discoveries and also explores his often rocky relationships with his wives, other women, his children, and his colleagues.",
        "link":"https://online.fliphtml5.com/jappq/rcjy/"
    },
    {
        "id":6,
        "name":"Frida: The Biography of Frida Kahlo",
        "image":"https://previews.dropbox.com/p/thumb/ABrN8R3xeMUShHzNrPidq0aLX7KleY9Cuhnp0efO9n46zBvItEoKa9JB1FG0bgPCV4dkAf8h3KkPW_e_aubVGTbqRnJiZc6tHgGUZRzoWAQqUzo2eyL6a_R-k_TxCVF_gOV96ZG9e1sd4nkL7bC5l7c6vruxxhYjiYwPxpcolh4Nynj5vRlG4KPtFQaURcVQtVRd7dSqyk2vPdzknt8ot9r6CJuQwF9F79dtaKFq92CWdy9J9zerg7KQyHgsIsS2b5RqASEUSqcg57abpNPhwPaz-uepIvxrDweA4145pijlh2b6cOq3hZsVsqXJCl0l1bOu7BkpAvSwU9Z5kA_RfBDjxUGsGw0FJ7YvRqo-E1UQ1CdKCw5UG7CI1fEI8YlG8yc/p.jpeg",
        "des":"A reissue of the beautifully illustrated and authoritative biography of Frida Kahlo, publishing in time for a major London exhibition Frida is the story of one of the twentieth century’s most extraordinary women, the painter Frida Kahlo. Born near Mexico City, she grew up during the turbulent days of the Mexican Revolution and, at eighteen, was the victim of an accident that left her crippled and unable to bear children. To salvage what she could from her unhappy situation, Kahlo had to learn to keep still – so she began to paint. Kahlo’s unique talent was to make her one of the century’s most enduring artists. But her remarkable paintings were only one element of a rich and dramatic life. Frida is also the story of her tempestuous marriage to the muralist Diego Rivera, her love affairs with numerous, diverse men such as Isamu Noguchi and Leon Trotsky, her involvement with the Communist Party, her absorption in Mexican folklore and culture, and of the inspiration behind her unforgettable art.",
        "link":"https://online.fliphtml5.com/jappq/fblp/"
    },
    {
        "id":7,
        "name":"Gandhi Before India",
        "image":"https://previews.dropbox.com/p/thumb/ABrDqyFILYwHrXejxuXsr0fBWiGb9PBmvDxundyRLszw8f06gEO8LqhE8Zm-I9lqLUT1mqSWpAXhqyj_gy5HneyU-KsxDYhlhROmOeaiS5jlcxOhgZsX7oXjcznGQN22KugYufz2DMQAKqphCwfTDoBQd4JwuuaAv8CF8QPCOfGXRXc1Fg9SgIJVpu02_5R7gGienJs5Xids1HKOG6k29ofuBvjo1TO_ppClcCuJx5Q_-3F_aceoouVD_IffP1yxf6Ke1UUIh0hW8EakJrq7TM5OMDpXGpWenMKd1v3OglHlqKkU4eesVwi-v8zbJf1LjX6iuAr-pZ9CTWdEmy8-l9t9QYbg81woiVutrV5xsCu6rYJIpB3hdnm04zLKrvT34qI/p.jpeg",
        "des":"Gandhi Before India, available in hardcover, is a book about the life of Mohandas Karamchand Gandhi, who is considered as the Father of the Nation in India. It speaks about the stories of his life that are not widely known, but which played an important role in shaping young Gandhi into a Mahatma.This book delves into the early life of Gandhi, the details of which are not popularly known to people. The author has traced the life of Gandhi from the year 1869 to the year 1914. This is the time interval which begins from when he was born, all the way up to the point he returned to India from South Africa as a lawyer. In Gandhi Before India, the author describes the childhood of Gandhi in detail. He also talks about the two decades he spent in South Africa, where he successfully carried out a revolution. The book tries to give the readers an insight into the philosophies and ideologies followed by Gandhi very early in his life.The book, Gandhi Before India, was published on 2nd October, 2013. It portrays a realistic picture of a young Gandhi. His experiments with different cults and friendship with people belonging to different religions is beautifully expressed. in addition to all this, the book also describes his enemies and talks about the failures he encountered in life.",
        "link":"https://online.fliphtml5.com/jappq/phgu/"
    },
    {
        "id":8,
        "name":"Napoleon: A Life",
        "image":"https://previews.dropbox.com/p/thumb/ABoZp8Fqdn03tWNuZJA3jUyNmZ-zk7J1-rBMwGRQxldv8HZjhVMXOfMw33yJJOPM7DsQUfhQcLmOT5cqGvtQgPcmpGsXbt0xh9AOrl9-_zX0OENI5wE6UML7nQCKeuLtpE8JFRTSCj3znGoLRlP-eP-AodJpmaXx72E7W48TgMo_n1S1b5ysV4pvEIQYx50DIjyhNz7rPd7xULIiUpNxPqPvCAnOOD9SoTark6ZyqYNv0hCXFOXzXFSg8Ht18Pm8CQUeNMRpzKL2GZOCpW7EoQPFS9ZBvh5ED8VoPixOFGecuulS5Nlr7pKD3BFpzMkddrgKkZ7i1ulr5FLyZtpLHJ6oGlwZ08Kt5maOXe1iOz2QelL9e5cddb9bavEBqpy8N-s/p.jpeg",
        "des":"Here’s another bio that will reshape your views of a famed historical tyrant, though this time in a surprisingly favorable light. Decorated scholar Andrew Roberts delves into the life of Napoleon Bonaparte, from his near-flawless military instincts to his complex and confusing relationship with his wife. But Roberts’ attitude toward his subject is what really makes this work shine: rather than ridiculing him (as it would undoubtedly be easy to do), he approaches the “petty tyrant” with a healthy amount of deference.",
        "link":"https://online.fliphtml5.com/jappq/ltoy/"
    },
    {
        "id":9,
        "name":"Steve jobs",
        "image":"https://previews.dropbox.com/p/thumb/ABouf9EQasjwhbOls1jXAigUDnWwkn6ky8cq_rqfD-_8yq8r3MwVj_Ktdl0Zxar43jyGz2zMKY2wDbz3CNCPrwXLPT756ulXFvB-Scf9Lsocy1sNk_cM3VnaQfo8e1KDSg87ne1qaFnLqa3No2VnDP9i_sQ0-DW3EgK378hN2Xx_uEYpy0y4cT-BVcCIHuixXH4A8IL_2sFF985YsPfVD5KTTyFRtZoNqJgh6_lfZAY-HuIS6KeQ7CvR6gWwKRsFUA0TwE9q1OevClH8SyK_XJJab65TwDW8bcx94chn5SKRaAmXRfmfySumSNZahZf7Fjz5maLSGmGBuRPr921RisuTAJW0Gci8FSWJtSxDzkOQgxa17DCozP5HO4kuH6pHjUU/p.jpeg",
        "des":"This is a riveting book, with as much to say about the transformation of modern life in the information age as about its supernaturally gifted and driven subject' - Telegraph Based on more than forty interviews with Steve Jobs conducted over two years - as well as interviews with more than a hundred family members, friends, adversaries, , and colleagues - this is the acclaimed, internationally bestselling biography of the ultimate icon of inventiveness. Walter Isaacson tells the story of the rollercoaster life and searingly intense personality of creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies,music, phones, tablet computing, and digital publishing. Although Jobs cooperated with this book, he asked for no control over what was written, nor even the right to read it before it was published. He put nothing off limits. He encouraged the people he knew to speak honestly. And Jobs speaks candidly, sometimes brutally so, about the people he worked with and competed against. His friends, foes, and colleagues provide an unvarnished view of the passions, perfectionism, obsessions, artistry, devilry, and compulsion for control that shaped his approach to business and the innovative products that resulted.",
        "link":"https://online.fliphtml5.com/jappq/ingq/"
    },
    {
        "id":10,
        "name":"The Theory Of Everything",
        "image":"https://previews.dropbox.com/p/thumb/ABorjAXLFKqmLrdimrZ9u7-7zfInjatiz4O1Xlazrtdgin9S5L6Enx95W4hpPp_Q7tTdc1GN0RDtw92DRWvkGhdN0TXWFcfmmM7Y3YzBPduGjQEvdtR7H40n1uCm1K8ndnJB1KdO67ZSMF1oXo_XWdnTvZIx25fOlRA8F1jgK8LssAY79hMW8fkMCtoza0gBYF7xdKo-pVrV0iKD9QiU5_umAN5h71kpXbftzN-QDoa8uMyArDVImVZqZy64Ibcssnw4dyNoXCaC1pxVkwyJ_hqBYd1Qa1tgk3UFq9JRdFodrlw_HLDdMQan6i7G7etnxR7GwAIdWzdRcL8yFAxV1mzd3l3vzQsTuiBJd5yfhbhzC8sgmRAPZjDlYl9Ml6rRpxo/p.jpeg",
        "des":"Seven lectures by the brilliant theoretical physicist have been compiled into this book to try to explain to the common man, the complex problems of mathematics and the question that has been gripped everyone all for centuries, the theory of existence. Undeniably intelligent, witty and childlike in his explanations, the narrator describes every detail about the beginning of the universe. He describes what a theory that can state the initiation of everything would encompass. Ideologies about the universe by Aristotle, Augustine, Hubble, Newton and Einstein have all been briefly introduced to the reader. Black holes and Big Bang has been explained in an unsophisticated manner for anyone to understand. All these events and individual theories may be strung together to create a theory of the origin of everything and the author strongly believes that the origin might not necessarily be from a singular event. He advocates the idea of a multi-dimensional origin with a no-boundary condition to remain true to the theories of modern physics and quantum physics. The book provides a clear view of the world through Stephen’s mind where he respectfully dismisses the belief that the Universe conforms by a supernatural and all-powerful entity. About the Author Stephen Hawking: An English cosmologist, theoretical physicist, author as well as the Director of Research at the Centre for Theoretical Cosmology under the University of Cambridge, Stephen Hawking is a scholar with more than a dozen of honorary degrees. In was in 1963 that Stephen Hawking contracted a rare motor neuron disorder which gave him just two years to live, yet he went to Cambridge to become what he is today.",
        "link":"https://online.fliphtml5.com/jappq/hopt/"
    },
]
export default Biography;