
const Business=[
    {
        "id":1,
        "name":"Invent and Wander: The Collected Writings of Jeff Bezos, With an Introduction",
        "image":"https://previews.dropbox.com/p/thumb/ABr1HaNGNT5yk4D4PM3RoTBbHd0AgvmxShlkRTkEsJzJ3bjrwGYSSgmV-lj2Hd6D0E2KuhEChJa8rXjhyJ87OVSjM-mPVUynVFLrL0Rp3ViZtCswOw8UeubCfigA_y1pVHpwWeV7XOVZ9rcPW2HCkKSW95ZZo8l5-i0RUmLnLp5-Mud0dxEf_Rqa_sOjyvzxsZn59olbwrjDCK-iGWpWVN7TCXIs_ozPHx7BxMKEz73LqXequzwmvaX0Wh5R04KCqVmeyOWBKBio2LPNFwxZ3gPYIpjRghwuu03QIO14n1RPlxQyaa3zhhpg9PxLJH89BMUPfhRoMCYEfQspNIfREaP4Kj3gd23aeosIf3hwINNGRGByOiVzZSVo9-ZIcEc_kQI/p.jpeg",
        "des":"In this collection of Jeff Bezos's writings—his unique and strikingly original annual shareholder letters, plus numerous speeches and interviews that provide insight into his background, his work, and the evolution of his ideas—you'll gain an insider's view of the why and how of his success. Spanning a range of topics across business and public policy, from innovation and customer obsession to climate change and outer space, this book provides a rare glimpse into how Bezos thinks about the world and where the future might take us.",
        "link":"https://online.fliphtml5.com/fxqlq/nwuj/"
    },
    {
        "id":2,
        "name":"Elon Musk: How the Billionaire CEO of SpaceX and Tesla is Shaping our Future",
        "image":"https://previews.dropbox.com/p/thumb/ABroLaVk4Fz79ccBTBDmeNiGjjj9q6vVNun9ERNUTu4vVFbzZdTA21qz9gpxcX0fD9J0HON9Edh3HmeMAcV16NAB2PosdCShRLS4z0J7r2d5o_jD5QtlavHtRigcb-viT9px5Qp2W9GHeEumHVSZdSgaAfVyqQ0vL5XJKtt4x7OnnyqCKVZBURW_Jl9gLt3HH-3O-Rt4fTyVLFKWUrf9EKHnLNYOvmvz6058Qp8sb-NW4M5FjcKsM_Hl9IO8AAMJiPfBZGlGxuWrcEnxcuBOqdIXVt8xIfMjDn4bFXSyHZ8OvE8G0aGeD-dnFb36edP6rIJzcwwpK2yT1FimQjO9E_7oLmcPMo67ZOrTpVBD8Z_yzdSHi0NSZ3X2kkMvA_ZporE/p.jpeg",
        "des":"South African born Elon Musk is the renowned entrepreneur and innovator behind PayPal, SpaceX, Tesla, and SolarCity. Musk wants to save our planet; he wants to send citizens into space, to form a colony on Mars; he wants to make money while doing these things; and he wants us all to know about it. He is the real-life inspiration for the Iron Man series of films starring Robert Downey Junior.The personal tale of Musk’s life comes with all the trappings one associates with a great, drama-filled story. He was a freakishly bright kid who was bullied brutally at school, and abused by his father. In the midst of these rough conditions, and the violence of apartheid South Africa, Musk still thrived academically and attended the University of Pennsylvania, where he paid his own way through school by turning his house into a club and throwing massive parties.He started a pair of huge dot-com successes, including PayPal, which eBay acquired for $1.5 billion in 2002. Musk was forced out as CEO and so began his lost years in which he decided to go it alone and baffled friends by investing his fortune in rockets and electric cars. Meanwhile Musk’s marriage disintegrated as his technological obsessions took over his life ...Elon Musk is the Steve Jobs of the present and the future, and for the past twelve months, he has been shadowed by tech reporter, Ashlee Vance. Elon Musk: How the Billionaire CEO of Spacex and Tesla is Shaping our Future is an important, exciting and intelligent account of the real-life Iron Man.",
        "link":"https://online.fliphtml5.com/fxqlq/kayk/"
    },
    {
        "id":3,
        "name":"Grinding It Out: The Making of McDonald's",
        "image":"https://previews.dropbox.com/p/thumb/ABrnl2ceWGKwCdRa4BjCjOBoH8_xvtK2d7PWCuESmbKzNoSjbmeb069UI9lD11PshN4zitcm8tuN2mZsb7NNdrFS70r3z0rBRfvDzhNsbXLDkXwfHl5WVAOLMxzkuj7KccTPYIqiJvpgCh6maEg8km0iioOkjrVHUbirZngh5EjwAJVOYeBSf7tbYFlQ0vzn6kgaYGc6VLjB_BaSFlSC7VkLb242IlyPpbB2wiJKNA0HhLsiNxGKt6BK1-XCNlWNRJW0Ayf8jQY01h_T7QoPhJ-rsKmyJEZcS9YT6imY9tgmex3RJERGjB-0Yj83G-TwZDnxlaiCEyPFF2e1dghfderz1G6WBzMQHdpIEttGny0EwY27gx5gZV5uN_7G7GitUTU/p.jpeg",
        "des":"Few entrepreneurs can claim to have actually changed the way we live, but Ray Kroc is one of them. His revolutions in food service automation, franchising, shared national training and advertising have earned him a place beside the men who founded not merely businesses but entire new industries.but even more interesting than Ray Kroc the business legend is Ray Kroc the man. Not your typical self-made tycoon, Kroc was 52 when he met the McDonald brothers and opened his first franchise. Now meet Ray Kroc, the man behind the business legend, in his own words. Irrepressible enthusiast, perceptive people-watcher, and born storyteller, he will fascinate and inspire you. You'll never forget Ray Kroc.",
        "link":"https://online.fliphtml5.com/fxqlq/jcqs/"
    },
    {
        "id":4,
        "name":"Never Split the Difference: Negotiating As If Your Life Depended On",
        "image":"https://previews.dropbox.com/p/thumb/ABoQWqePy29oiSnoSvy27Q3XedzpjxwnWgN9al7UpX5cfhrq3HwqDGBhqPlWgbUqMTVd4iQuJqK4P9xW1n0BQ6BEXfrFGjImYP8NPVJnLOGT4lWYH2PvcY-NR2GAAQWRI2mbRhNMPG6nKj-MgG2qqBvDRVC1H_SQLjcFcBxGxOaWHDl3zGJdWObCOaJa2fPigO3l2ijYkSEXrtOj-VAO5qt16eBVIwazXzUhC3qVbOtP8EukxmTlAKdsT8p7Tz_BD00zBg3rvh9lRKBo5EXSQ4ko6tNxsml9T6gzjJrwz4YKVMwxc_YyQqoJcDp4Y_5GCu-vtIKlm2MFj9rhJmegf6ZAqHdJWDtc-0oZhXk5qILwArC2yuVZskPs4DMTQlwESFw/p.jpeg",
        "des":"A former international hostage negotiator for the FBI offers a new, field-tested approach to high-stakes negotiations―whether in the boardroom or at home.** A Wall Street Journal Bestseller **After a stint policing the rough streets of Kansas City, Missouri, Chris Voss joined the FBI, where his career as a hostage negotiator brought him face-to-face with a range of criminals, including bank robbers and terrorists. Reaching the pinnacle of his profession, he became the FBI’s lead international kidnapping negotiator. Never Split the Difference takes you inside the world of high-stakes negotiations and into Voss’s head, revealing the skills that helped him and his colleagues succeed where it mattered most: saving lives. In this practical guide, he shares the nine effective principles―counterintuitive tactics and strategies―you too can use to become more persuasive in both your professional and personal life.Life is a series of negotiations you should be prepared for: buying a car, negotiating a salary, buying a home, renegotiating rent, deliberating with your partner. Taking emotional intelligence and intuition to the next level, Never Split the Difference gives you the competitive edge in any discussion.",
        "link":"https://online.fliphtml5.com/fxqlq/bnbt/"
    },
    {
        "id":5,
        "name":"Profit First: Transform Your Business from a Cash-Eating Monster to a Money-Making Machine",
        "image":"https://previews.dropbox.com/p/thumb/ABoj734LOmYSmHyGJXCXEHMT3_D0faYYcgpGs_gBa50u-pf63zIpKLtj7etorBT4xUIeRDtmJ10doDN1rzvCBkTcbU82Ba3_V-boTBooHEzkaSsxbUly3OjrC5CaNGoRdDm2QSG0PfYFgFvEw9-L105_f-IE-8K5Zm_XzD5t5w_aVIt8Fa6hSoIvHt7Nl9GvC-4gfdaonIyeDj0BJJyYMrVqRS20EIupuJ00Y7yRpSQDxeOVILBtH5huGYVkaBJFyXpqipbybeq_K2Ue32zOluTCtX9_ZNUY_j0u77bTRHs2jFdZ40ukgP7a1xwfJILCu8OVGLfi3eTTjXMudpnAHWQ7XwnzDOg_EedR9cWPsx7smFS1Oj5JAOPAkY62P-Gl-4M/p.jpeg",
        "des":"Conventional accounting uses the logical (albeit, flawed) formula: Sales - Expenses = Profit. The problem is, businesses are run by humans, and humans aren't always logical. Serial entrepreneur Mike Michalowicz has developed a behavioral approach to accounting to flip the formula: Sales - Profit = Expenses. Just as the most effective weight loss strategy is to limit portions by using smaller plates, Michalowicz shows that by taking profit first and apportioning only what remains for expenses, entrepreneurs will transform their businesses from cash-eating monsters to profitable cash cows. Using Michalowicz's Profit First system, readers will learn that: Following 4 simple principles can simplify accounting and make it easier to manage a profitable business by looking at bank account balances.A small, profitable business can be worth much more than a large business surviving on its top line.Businesses that attain early and sustained profitability have a better shot at achieving long-term growth.With dozens of case studies, practical, step-by-step advice, and his signature sense of humor, Michalowicz has the game-changing roadmap for any entrepreneur to make money they always dreamed of.",
        "link":"https://online.fliphtml5.com/fxqlq/jzyt/"
    },
    {
        "id":6,
        "name":"Secrets of the Millionaire Mind",
        "image":"https://previews.dropbox.com/p/thumb/ABqJmfcNiDt8L2pI0wSawroMplE7anNlhP9eVU960XMldiuKjgHvO7Ac1feKtiS8t3z89CKt_QI382-nc0jSFy_L9GzxrVC3GswZAAvJ-zQ-qTXGf4E0AASNIiHm_TnsXNjTofuH4fH2FXXfXVDhN3iZREZ1MLdG3jTGVLqAYIgq-eMeSTbQRoPdGAHHJbedoDFitqSMd6xyaw6lrG4gSHNjm0cEY2eDri56O960TzG2N-W0zCeAPja9hmF73YS2LYGVMWozojgbFbHDMbLzlzsLnsMgf-rv0NroxQtlGDKtHJRb9uCC4lWH0ItmOinbZcfKTjqs4eW4l4FjoWMnpiqUWRsfPzkT1d6DRoDMt0LOGfg_QvCa82EpjG_U3rkc6f8/p.jpeg",
        "des":"Secrets of the Millionaire Mind reveals the missing link between wanting success and achieving it!Have you ever wondered why some people seem to get rich easily, while others are destined for a life of financial struggle? Is the difference found in their education, intelligence, skills, timing, work habits, contacts, luck, or their choice of jobs, businesses, or investments?The shocking answer is: None of the above!In his groundbreaking Secrets of the Millionaire Mind, T. Harv Eker states:Give me five minutes, and I can predict your financial future for the rest of your life! Eker does this by identifying your money and success blueprint. We all have a personal money blueprint ingrained in our subconscious minds, and it is this blueprint, more than anything, that will determine our financial lives. You can know everything about marketing, sales, negotiations, stocks, real estate, and the world of finance, but if your money blueprint is not set for a high level of success, you will never have a lot of money—and if somehow you do, you will most likely lose it! The good news is that now you can actually reset your money blueprint to create natural and automatic success.Secrets of the Millionaire Mind is two books in one. Part I explains how your money blueprint works. Through Eker's rare combination of street smarts, humor, and heart, you will learn how your childhood influences have shaped your financial destiny. You will also learn how to identify your own money blueprint and revise it to not only create success but, more important, to keep and continually grow it.In Part II you will be introduced to seventeen Wealth Files, which describe exactly how rich people think and act differently than most poor and middle-class people. Each Wealth File includes action steps for you to practice in the real world in order to dramatically increase your income and accumulate wealth.If you are not doing as well financially as you would like, you will have to change your money blueprint. Unfortunately your current money blueprint will tend to stay with you for the rest of your life, unless you identify and revise it, and that's exactly what you will do with the help of this extraordinary book. According to T. Harv Eker, it's simple. If you think like rich people think and do what rich people do, chances are you'll get rich too!",
        "link":"https://online.fliphtml5.com/fxqlq/jtaf/"
    },
    {
        "id":7,
        "name":"START-UP NATION:-THE STORY OF ISRAEL’S ECONOMIC MIRACLE",
        "image":"https://previews.dropbox.com/p/thumb/ABpXC7lA_-B0GHz3TCo2yVq48KCCKskk62gUn-lctsNJ_OcUkWBzVef-XvE8G5hsnectClWaq3KIuq2daYo-sTQaC0xnG_9rTm0as9BYLCTyuTLK1NAEeDgAi0gZbUgKhhN97S8V_tE0Cy8fXDDPHiLhYCeCUQutRCK3AMy_MG9s_ZIYQLAK9ZGJ_YtPzQG-H3va9gLTeUaoLXSj3ntrf-oZHnntqIHIbkouSN0_SpJdEpzC1j-A3qqt_FBV-psQSK-f3YarQEo1D3rvUaAK1XkufELv43ISRg91hcni-MbSSNYPO0v6iXqC3mZLLr1N6zxixgxzvWiejA7PNVWXv1cPEQlUxXxapAxiOtPm-mQo2pxNMjgc2Hpovoz1EYvzLv0/p.jpeg",
        "des":"START-UP NATION addresses the trillion dollar question: How is it that Israel-- a country of 7.1 million, only 60 years old, surrounded by enemies, in a constant state of war since its founding, with no natural resources-- produces more start-up companies than large, peaceful, and stable nations like Japan, China, India, Korea, Canada and the UK?With the savvy of foreign policy insiders, Senor and Singer examine the lessons of the country's adversity-driven culture, which flattens hierarchy and elevates informality-- all backed up by government policies focused on innovation. In a world where economies as diverse as Ireland, Singapore and Dubai have tried to re-create the Israel effect, there are entrepreneurial lessons well worth noting. As America reboots its own economy and can-do spirit, there's never been a better time to look at this remarkable and resilient nation for some impressive, surprising clues",
        "link":"https://online.fliphtml5.com/fxqlq/mieh/"
    },
    {
        "id":8,
        "name":"That Will Never Work: The Birth of Netflix by the first CEO and co-founder Marc Randolph",
        "image":"https://previews.dropbox.com/p/thumb/ABo9t1xPh_uMeYigZjav-FJr44I8-Ssb7lg6gWe1O1zOtzxoGCaSnlpkRe1lorl98XZMSOV4CKzFYAqNIDdqJU4qZc16pm4m5lsTdY9xP3iTQjT8WUa5OUPQ4ewSkWDJkep4a97FX-Ugx9pBTPs8jPXYwn9KCApVfc6tN_rXRhGKWVQOqyHynkoAbcG59FUAO5y-ChyNOSibyS0qXRqHLviDqbratfDa4aj6jJ9cSuA5ziB5xymEbpdhIrnAftN3k8WcoBf5z9JrMtyLjrgVMcECU55u1b6jirEeglezUrCIlo23pDzUa-m0VSmaHb8MJFkq2-pbaAAeLmFFhbJ9PCZpyNsNJXBVw-KFxnUs0VuuRZUeyO-FH0_vOmMgz3uTVPU/p.jpeg",
        "des":"Once upon a time, brick-and-mortar video stores were king. Late fees were ubiquitous, video-streaming unheard of, and widespread DVD adoption seemed about as imminent as flying cars. These were the widely accepted laws of the land in 1997 when Marc Randolph had an idea.It was a simple thought - leveraging the internet to rent movies - and was just one of many more proposals, like personalised baseball bats and a shampoo delivery service, that Randolph would pitch to his business partner, Reed Hastings, on their commute to work each morning.But Hastings was intrigued, and the pair - with Hastings as the primary investor and Randolph as the CEO - founded a company.Now with over 150 million subscribers, Netflix's triumph feels inevitable but the twenty-first century's most disruptive start-up began with few believers and calamity at every turn. From having to pitch his own mother on being an early investor, to the motel conference room that served as a first office, to server crashes on launch day, to the now-infamous meeting when they pitched Blockbuster to acquire them, Marc Randolph's transformational journey exemplifies how anyone with grit, gut instincts and determination can change the world - even with an idea that many think will never work.",
        "link":"https://online.fliphtml5.com/fxqlq/jvjf/"
    },
    {
        "id":9,
        "name":"The Psychology of Money",
        "image":"https://previews.dropbox.com/p/thumb/ABpZ3zKCB_cGcGNnZcIyLOB_k3YEJ9qrEDtICIYRfRv80qzyd5diBM_0xtdcVfgz4PIILHac0q93PlRdBkwm9roHaNWVW4PBfTiFEygV_TdZ7HlZdTDovlIBV6BBcnu2wp8GUJlwbs_tqytfX5X0HnvyP9DL-IfiTGxdkEf5JfZRGivwjLmGV9QbY8W3dMiJ97l55Uto7rX3fc5rq-b4Zr9EvqefsuMeuGgoliqF71gr0gV0QCnTwkPcaNIM9xzVPXeeKzmEKOJntf8Jxk1kSyY3EgUTKCOM_BoAH3CLxU2ih7HadBtGFjp4yQZhIco3FsTxycnhziVgRmribAwvt9hYXlAGCSQMVKxTZjg79_s3yy5WNREkRNxwxRFKpoQw5KQ/p.jpeg",
        "des":"Timeless lessons on wealth, greed, and happiness doing well with money isn?t necessarily about what you know. It?s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don?t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life?s most important matters",
        "link":"https://online.fliphtml5.com/fxqlq/yccj/"
    },
    {
        "id":10,
        "name":"Think and Grow Rich",
        "image":"https://previews.dropbox.com/p/thumb/ABqBzh2MJbhSZH0T3H1s2Dm-M8W8tOj8BYAo_8mcUhaQ8VWx_QOBD30oHrfrFnlkT9y0BedGoeR0X7vJjzK_N-RfYxIHHspA5LCYZ72-3m_ZRbi8vXTUV1OENRoP-bOkeaLj7fyd5EOT-TRaKHiXzg_xWMRZCKRs1z1p2RKcHo7djsff_iOZRLfHPt_1YfyYX5CMIhFbw2Z_lN5oCi_8qR_pq8PosNbvuM3SFtdFzeyn5Qo1dMYqnBYDECVBXbY39970m5V3CtgkjIqCmil-OlflQtlvzgSRNORX7WDMcounpYKKXLBCjvP8_LU2jbz1Qz6vtjNiPOf6ptBZkA3cmXmChw64u3zOuY5KtoW6nF74dZcy65ouwIuIBWgTmQPps_Q/p.jpeg",
        "des":"Think and Grow Rich by Napoleon Hill is one of the bestselling motivational books of all-time. Inspired by a suggestion from industrialist Andrew Carnegie, Hill explains the philosophy that helped the wealthiest and most accomplished members of society succeed.",
        "link":"https://online.fliphtml5.com/fxqlq/sezt/"
    },
]
export default Business;