const Health=[
    {
        "id":1,
        "name":"Being Mortal ",
        "image":"https://previews.dropbox.com/p/thumb/ABp5n2FXYbx6Q3bVtzDIafrbnBloDVNgrodMymp2GQTmzZGOerLkB5XPkeMgTZKVTa2oWPINGXzD8EyQ1ukZ34Vbj6L21H7tZRK_7cvDTgPHrqp5QBxoPvijNfb1-r_uIJuoQvnTWTnYdq29wkO_NhiP1PwEQUndZNYwBbA60FpND7Bj-q3wONe31BIocaScfDn7SAPHVSB-DYCOJ7rOn_kDzwARb3ymUjg4xxi_vsyr4BB4zjALAD7e6UeQLMM6Kd4SKlI-fQhq5jC7AZPxlUsZEeJtbSQqebyDVEhp9jt3zWoWVXmxtTEeqEJGTjfPDY9ycwVsf6Q5RUizZxy-8JS5v73ShtqvBjn9JH-zzW53yRF2s8ielMGzfGYfUstBTfA/p.png",
        "des":"how medicine can not only improve life but also the process of its endingMedicine has triumphed in modern times, transforming birth, injury, and infectious disease from harrowing to manageable. But in the inevitable condition of aging and death, the goals of medicine seem too frequently to run counter to the interest of the human spirit. Nursing homes, preoccupied with safety, pin patients into railed beds and wheelchairs. Hospitals isolate the dying, checking for vital signs long after the goals of cure have become moot. Doctors, committed to extending life, continue to carry out devastating procedures that in the end extend suffering.Gawande, a practicing surgeon, addresses his profession's ultimate limitation, arguing that quality of life is the desired goal for patients and families. Gawande offers examples of freer, more socially fulfilling models for assisting the infirm and dependent elderly, and he explores the varieties of hospice care to demonstrate that a person's last weeks or months may be rich and dignified.Full of eye-opening research and riveting storytelling, Being Mortal asserts that medicine can comfort and enhance our experience even to the end, providing not only a good life but also a good end.",
        "link":"https://online.fliphtml5.com/yktxg/idxe/"
    },
    {
        "id":2,
        "name":"Born to Run",
        "image":"https://previews.dropbox.com/p/thumb/ABq-qNAHVFKmW2eqtbq6zWxm3iDxYrU82PMliqCRuho3cSHadnREt974JmDSFmK2DlDB5NUloRNLfLZQQxukwg3S50T3Ies0pQfPRRdht1usbhBfaKfAwwOyUQlWWUFjDBhY5RvDbW7Bes-2hNJobB89dEuSL74-LjQabHTHEIXwIHMjs1epBLo_FYKWHvIEKbat5JovcyWA3SJtdjQ2IJChORAWEob5IneSa-JlVvSXJvJbL_uBCVpHK11UypP_SWYGhSEgo_j1pJJMIx3ACKBHrerLDYjAYskuWD8ekRq90OHO0gOlAc9hWDt3mzccJzDQx5fb4WnePLDZWdVFhkInSkYqLllvg9A5SzSxQTo5MpNFqs3xefvVHWHLDbIsgdI/p.png",
        "des":"Outside MagazineIsolated by Mexico's deadly Copper Canyons, the blissful Tarahumara Indians have honed the ability to run hundreds of miles without rest or injury. In a riveting narrative, award-winning journalist and often-injured runner Christopher McDougall sets out to discover their secrets. In the process, he takes his readers from science labs at Harvard to the sun-baked valleys and freezing peaks across North America, where ever-growing numbers of ultra-runners are pushing their bodies to the limit, and, finally, to a climactic race in the Copper Canyons that pits America’s best ultra-runners against the tribe. McDougall’s incredible story will not only engage your mind but inspire your body when you realize that you, indeed all of us, were born to run.",
        "link":"https://online.fliphtml5.com/yktxg/wkhd/"
    },
    {
        "id":3,
        "name":"healthy living book ",
        "image":"https://previews.dropbox.com/p/thumb/ABpMjPQSRUI2iRH6O_BssLk72un8FPlYBYURxmwD1n9UNZotaRI9osVcvy1gzIFH4OBrYGwx1OrGa4ocS10rdeM1O5_zJFt-8ALPl10dKkxI7gmoUSCajqwaQAzClTGptKH_gJc0WILBWM48A-RwSVMlly5WNZqyZK6Lqeob5u6pD2vVZWHdmA1AwP8pBFXDhSh2R7PBgZwuRtlsj00RPbRP7Kg0ht0LeWvJ1pct7nu5ZLT09XD1JoD9AtYDymcIlp6F82mdETVZ51RYU223J-VtCNqHJbS50MIRbMgwZYYbZ3COoUFl7ihx4nne2DPcjNkAx_iEFHWX1KTcCMj8qsnCmm4VVC1Unj8pVfhV2YysrChHLyYdiRbzu2Ffka62DFE/p.png",
        "des":"The Sanctuary for Health and Reconnection to Nature and Animals (SHARAN) mainly helps people reverse diseases through nutritional guidance, but also helps people connect to all three of the physical, emotional, and spiritual causes of disease.",
        "link":"https://online.fliphtml5.com/yktxg/nkji/"
    },
    {
        "id":4,
        "name":"Don't Lose Your Mind, Lose Your Weight",
        "image":"https://previews.dropbox.com/p/thumb/ABp8MwE0RZaJ9SV-x613TEGMRBTcrtlH7dzbuzXY4TbzZDv_xSXNyPMCckK06WcW5JEYRKxpsMVPinIDLglqjT0iUXIgtoFgRMlP1hEQMSF9lcvvUWd9QQa7p-sypjc5CSu3dvJYsQrsIRzVYOVaHIsiUS9ZmFluURPuiaYhyJOu4HjqsTsM7VxjFray8LWackF4tFry4aU7KM6pBaaN4LP8x3ZFtqKt4cNEybtvMsqoZtTGhkzye75xd4Cyh1s71d1jSgh1vCTNe3vv3D8OdlaK22rt2CTl0U9GMmVC0DEeLNunTXd_FMtJw1CqG5D_3UImdBLjKE_nJvcn3QjHOd2FTZzO6iR3ruUMvG3VOXDQZJZtb9dxY_jDjoANTYDHdcI/p.png",
        "des":"'Don?t Lose Your Mind, Lose Your Weight? is considered as a path-breaking book by many as it which has helped them to lose weight without giving up on food or without leading them to periods of crash diet and bad health. A celebrity fitness expert to whom many Bollywood actors and actresses owe their great shape and health, Rujuta Diwekar speaks to the readers in clear and simple words how a person can eat anything s/he feels like and yet remain healthy, maintaining a good shape. As a leading nutritionist, Diwekar is against the idea of any crash diet that looms over carb-starvation, needless food cravings and other similar things which ultimately lead to a food deprived body. The book guides the readers through certain simple steps to an ideal way of dieting or maintaining a healthy and proper diet. It helps the user understand their own respective bodies and likewise helps them plan their own diet according to the bodies requirements. Since she is the celebrity dietician behind many leading Bollywood actors, Ms Diwekar often cites the case of Kareena Kapoor about how she was able to attain the size zero for the successful film Tashan. Her book shows how one can indulge in their favourite foods yet manage to shed calories at the same time. Referred to as a marvellous and helpful read, this book was published in 2009 by RHI publishers and is available in paperback. About the author: The author of 'Don?t Lose Your Mind, Lose Your Weight?, Rujuta Diwekar is a celebrity fitness expert who won instant success with her book and was bestowed with the Nutrition Award by the Asian Institute of Gastroenterology in 2010. She has also received accreditation from Sports Dietician, a fitness organisation based out of Australia.",
        "link":"https://online.fliphtml5.com/yktxg/uuxe/"
    },
    {
        "id":5,
        "name":"30 DAYS: Change your habits, Change your life",
        "image":"https://previews.dropbox.com/p/thumb/ABqDviOalQnD4gAv9aUPN8XaqraJtexaPNnvb2zaKbb8S47NXIRQ8Ulz4_PMM7uPzwOs_Wcp41mfrZbwDb7fI0U9fkL_8a6cWzc3n5q354VD1pXE96BeuKYESwPOzs5Gt2fWIt3YRMYXYKq3UrTLi4o5NjIyk3L_2AzVL7a3h9NZgIdUF5Qds1GjGn_6IAW8pE3PXqIfZm_FiReKn35tbFoFU8fVx8I7gRMvyHqfCelS2TbRFHeqyGvocYj5Wdx1i14kvpkk4aRv2gBk3KEl0wC5hI6zuKepbF9SfIn1VUpKtl_8vyYdIyF9LaWwEX40rd4rO2kyE-cUHfB1FlMFR5HABCuKhT3tL2pN6JonuBaLROZE1GJ6YDmDprrxDBWRjOY/p.png",
        "des":"30 Days is a simple, fast-paced book where you will learn what it takes to create the life you want. In this book, international bestselling author Marc Reklau introduces the readers to some proventips, tricks and exercises that can improve their life beyond imagination! All it takes is following them constantly and persistently.s",
        "link":"https://online.fliphtml5.com/yktxg/viea/"
    },
    {
        "id":6,
        "name":"Pregnancy & Childbirth: Everything You Need to Know from Conception to Labor and Delivery",
        "image":"https://previews.dropbox.com/p/thumb/ABraPablrrjFscN7hQju1-S8sRDKO_8RTQ9g2-TNF2Jq7KJc1ndV6Ycs9HK9HSrrs7_rI_HnvYlFB2x3BrYYwJ1wWpsLahyTGJwielyuInhSU_c3nigr75FkrIXuaBLNTDEbldH4u48XRqTnhv5AWrnQQaM_BB9gdq0Cv3KiqbUNnQYlF-LG47_5BWAbduhzRtGgCp408JrJeBTrUTJXJ5o1WS5c2HkqbniTipdv9m-mdSPVH-0U8mJKbwCah-ViIe5PVIJy1dymcVOPSs78VKBpbiFy3poQWX3nJBLhkJS9-VwUxDaj_LONAnb89Y4aFKguHCNuoJ9LPNWVoAEgZxV24IiHgHVydF8kwzYFZirNCwBBC8LDNWWxaVgPnxM2gr4/p.png",
        "des":"About the BookThis book is a guide to pregnancy from conception to birth and everything in between. You will learn about methods for diagnosing pregnancy, tests used to determine how your baby is developing and the importance of communicating with your practitioner. You will also discover the importance of the pregnancy diet, prenatal vitamins and what things should be avoided during pregnancy, from tobacco and alcohol use to the use of illegal substances and caffeine, all of which pose negative risk factors for the development of your baby.You will also be provided with an outline of the next nine months of your life, including what you may be feeling emotionally and mentally, reassuring you that crying over spilled milk during pregnancy is often acceptable. Further, there is information on what you may be experiencing physically, from being exhausted and having to constantly pee to feeling nauseous and constipated all in the same day, again reassuring you that this is perfectly normal.The goal of this book is to provide you with the information you need to conduct a safe and healthy pregnant environment for your baby to grow and develop in. It is not meant, however, to scare you out of your mind with the different complications that can occur during pregnancy. If at any time you are reading this and you begin feeling overwhelmed by the information or are unsure about anything, ask your practitioner. After all, you chose this individual because of their expertise and experience in the field of pregnancy.With that said, sit back, put your feet up and enjoy learning about the life you should live for the next nine months while there is a child growing inside you, completely dependent on you taking care of them. Relaxation, rest, adequate nutrition and fluid intake are essential. So, grab a glass of water, read a few pages, take a nap, read a few more and become the best pregnant mom you can be! Oh, and don't forget to go pee, because it's likely you need to after reading this introduction, even though you just went five minutes ago!",
        "link":"https://online.fliphtml5.com/yktxg/eubc/"
    },
    {
        "id":7,
        "name":"The How Not To Die Cookbook ",
        "image":"https://previews.dropbox.com/p/thumb/ABqz4RgaRfV-oeUwQOW8Pd3YhwdQtK10Wr5BuWQR9CjkC5IBM_QQXQIIyTuBD7a0YU9SOm-TyeEjPbnBdoVHqpYkAp2xQIk-S9pKuhl3_kxbKRuIu4DXP3VeTNRTKcIWD6USyo6jP4h8pSUBpWWUMix_NOEc0GUKV7bYk-Qc7_oOToupeKYwv1Q5so2zvysaPKb_OZQqM6JvgLif1lbFKYSi2WUWW5WK0QEEOm6Rs5AA8stLHCIgLKReaVJpzJ5GJpK7n515VkHx5UT8IGchku2aDbltJA2Ft4iZYT--fnNEhlkdYItVkBynSLKFm63w_mMGitPx3uN6zpKuJsZEN4PcG3MHhLkS7awAaCQW5ZcYnFeoR2vYSM61PirgSzSfrzg/p.png",
        "des":"beautifully illustrated collection of delicious recipes based on the groundbreaking nutritional science of the original book. Dr Michael Greger, founder of the wildly popular website NutritionFacts, takes his comprehensive, lifesaving science into the kitchen. Why suffer from disease and ill health when the right food is proven to keep you healthy, and without the side effects of drugs? We can avoid heart disease, cancer and our other biggest killers if we use food as medicine, and the How Not To Die Cookbook offers a sustainable and delicious guide to preparing and eating the foods that will prevent and reverse fatal diseases.Featuring over 100 easy-to-follow, beautifully photographed plant-based recipes, with plenty of recipes suitable for vegetarians and vegans, the How Not To Die Cookbook merges cutting-edge science with everyday ingredients from the supermarket to help you and your family eat your way to better health and a longer life.All recipes in this cookbook have been fully anglicized.",
        "link":"https://online.fliphtml5.com/yktxg/csdv/"
    },
    {
        "id":8,
        "name":"Unlimited Memory: How to Use Advanced Learning Strategies to Learn Faster, Remember More and be More Productive ",
        "image":"https://previews.dropbox.com/p/thumb/ABpGK_SCvUjhq98KLoJP80t3FUIsO0gyICistabFnvArQeEAnam6vjWgHJcNH1kxkcvEV0c2Q33OlwlR3ruJYBfZj8iFVGFfFJea-kMS7CDlFPiki1qiovvJa8I20uSiHBvmdbDdJcoAAz_sDpNA8VIv8pK0E60bgZ8p8sv5DDZ1byl1cTDNyuh9rkvdB10kDTcPn3EwjdQq34trSl1I2VMYN5YrHcy87e-dYuK5o4aX34C4Ox8fl4syMXnLgabGnpZjwo4mPoS1mFM93TplZmNUEyLSUdEFyl1MnhzY9u-iIvvJdx4fajT6TYjdmECtJN-nCdrrNhgHGwrwQYPx-s0AEfoANrzp2mJ0Tw1Q9g41qFla1-m8q7lQF11kJi84vGs/p.png",
        "des":"Do you ever feel like you're too busy, too stressed or just too distracted to concentrate and get work done? In Unlimited Memory, you'll learn how the world's best memory masters get themselves to concentrate at will, anytime they want. When you can easily focus and concentrate on the task at hand, and store and recall useful information, you can easily double your productivity and eliminate wasted time, stress and mistakes at work. In this book, you'll find all the tools, strategies and techniques you need to improve your memory. Here’s just a taste of the memory methods you'll learn in this book",
        "link":"https://online.fliphtml5.com/yktxg/zpcq/"
    },
    {
        "id":9,
        "name":"Why We Sleep: Unlocking the Power of Sleep and Dreams ",
        "image":"https://previews.dropbox.com/p/thumb/ABoudMo6qjCg02DNMCyw1-6XfKjeR4Iz8gcRGEspBR6ZZP9SCAUtrMNTZR9lvzVm0C_q2s_SNBX_XNTXzxuK9pqG8O847Lmyo7_FViEXkOT5cHFfZVWass2G8xQVcBbcULYdWWDEJ7yppDNuaAAeh3MvRqizRUm0XBrgOpUTA0kXrTuyaiY5n0RplCU5avXvEW_nHKjpeeZn1edLZgSpXcQwdWfHqNGR2yuEG41f1zduNrzZXKW2rAhgwQNjJj92uKClVxsTP1tkoAq8xMDAZAEm1q2nqVkp7-PzhxpS91g-RN-D_cCyJ9cigkfU5irQHed7De5Jd6suAztYrGrQLXPr8o0w2_b6OOpXyHaLgT0aU8_RdXMwYKWPZuGZdsTJZ48/p.png",
        "des":"Within the brain, sleep enriches a diversity of functions, including our ability to learn, memorize, and make logical decisions. It recalibrates our emotions, restocks our immune system, fine-tunes our metabolism, and regulates our appetite. Dreaming creates a virtual reality space in which the brain melds past and present knowledge, inspiring creativity. In this “compelling and utterly convincing” (The Sunday Times) book, preeminent neuroscientist and sleep expert Matthew Walker provides a revolutionary exploration of sleep, examining how it affects every aspect of our physical and mental well-being. Charting the most cutting-edge scientific breakthroughs, and marshalling his decades of research and clinical practice, Walker explains how we can harness sleep to improve learning, mood and energy levels, regulate hormones, prevent cancer, Alzheimer’s and diabetes, slow the effects of aging, and increase longevity. He also provides actionable steps towards getting a better night’s sleep every night",
        "link":"https://online.fliphtml5.com/yktxg/quzz/"
    },
    {
        "id":10,
        "name":"Yoga Anatomy",
        "image":"https://previews.dropbox.com/p/thumb/ABow4pZGmXh55CtylQVqSsjd8Old50yneeyrMxHqEsAj9HN35CF90VHknXEVjVa7b6d9Smky3A45KuunRiGXVQTp0l8dIGLFdz_tJc9UhDS-PAYdJvI0n6F4M_5kynYoUbkJViuvKsBYGNlp1uNqi3_XMtvejCYtxQ9czKtKsydCfcEpFeAmi-eGK0jpskUQQ8dMBh0PtE_WOIXJ3dlLJWJryE7wry5K36w6fIJNl1-hLb-egn1-L1BVx1MrafSRBoi_gLghBWzy94rf_-hytjqMLoTbCVEB4SmwczDSm1RNOlGcUqMj_15y_XuOf0jAvvzhQw3EqybC1rssZAPbHE8VGPDs7SirMwjALSzUqYCrtIBcLWc0JJ1LYidclmdQGmU/p.png",
        "des":"with more asanas, vinyasas, full-color anatomical illustrations, and in-depth information, the second edition of YogaAnatomy provides you with a deeper understanding of the structures and principles underlying each movement and of yoga itself.From breathing to inversions to standing poses, see how specific muscles respond to the movements of the joints; how alterations of a pose can enhance or reduce effectiveness; and how the spine, breathing, and body position are all fundamentally linked. Whether you are just beginning your journey or have been practicing yoga for years, Yoga Anatomy will be an invaluable resource one that allows you to see each movement in an entirely new light. with Yoga Anatomy, Second Edition, authors Leslie Kaminoff and Amy Matthews, both internationally recognized experts and teachers in anatomy, breathing, and bodywork, have created the ultimate reference for yoga practitioners, instructors, and enthusiasts alike",
        "link":"https://online.fliphtml5.com/yktxg/ndjs/"
    },
]
export default Health;