const Technology=[
    {
        "id":1,
        "name":"The Architecture of Computer Hardware, Systems Software, and Networking",
        "image":"https://previews.dropbox.com/p/thumb/ABqM3J2S-rDREFXgIB4g2p2XlegvYa0MVnAPJmsMuhugjFCr2dbSJ2gsLB95SsuOnGTGLOWWRfM81Z630kDvKOx8ELgNvJFqTOoEGNe6GqxO4bho8N3UJZeC7TeMO5-5qcz9BvRIutIdXX42WA2892l-CGeDA2BvrK8ByDK3RWobyIudHf2rCWXL8nariTig-P_cO2IMz0a7a9VW_w2-pQHx1IZ1BXKFF2Z5ZrO9JpORzvJEJac8begRNu98rRaLgkMHI9tqXsazBehPCFhSigCUP2qxrxB3tenOHF5oxv6uzb56kKGSgW2mLYHkon6SO5jVree3q7R5TSXmqRznnLta9avTidtpkVPDOz22ORsBEocVZ5NXdyL3Obdqqa1WpZE/p.jpeg",
        "des":"The Architecture of Computer Hardware, System Software, and Networking: An Information Technology Approach, 5th Edition provides the right amount of technical detail needed to succeed in the field. This accessible introduction provides the basic principles of computer system architecture and organization in the context of the current technological landscape. The author provides chapters on the fundamentals of networking as it relates to computer systems as well as all kinds of business systems, from entrepreneurial to small business, networked, distributed, and more. This valuable book provides IT professionals with several real-world case studies that clearly show how the concepts are applied in the field.",
        "link":"https://online.fliphtml5.com/fxqlq/axaz/"
    },
    {
        "id":2,
        "name":"Data Analysis With Microsoft Excel",
        "image":"https://previews.dropbox.com/p/thumb/ABoR1jOS8NPGEZoE1XFgiqDG5Cbd1Ey46VXF0JjDrgvjgdquEdp5thmuZMxpvXG_gspMkurbKd8xkadU_0ELiYXYh-8A4xrcrRkfC7DZHqQy8aIF5N2qLKflNN-Zw6-y7S5Bwwxx7CwRPuWU58aBhLngtQZ1xDNmkC_xHho_q7M-1wx80chxfbDoavv7triYVDOTIjvAtL0qpqsXf0eCc-QMg6D2CUCzmPmyUfI09iExUABj1rX7rxY7dpPRgjlaxpE2lxgoY85IkNtm6-NHD_6ODNiX0STpNtSdjmqLo2lJTCgvfmkDcOiKgM12RUekgrI5L4JYWs0PeBusy3ZyvgaPm-xqmkH3QfBuWvK-N7xJ1GEpchiPoi2z9E0HReyOLww/p.jpeg",
        "des":"This popular best-selling book shows students and professionals how to do data analysis with Microsoft Excel. DATA ANALYSIS WITH MICROSOFT EXCEL teaches the fundamental concepts of statistics and how to use Microsoft Excel to solve the kind of data-intensive problems that arise in business and elsewhere. Even students with no previous experience using spreadsheets will find that this text's step-by-step approach, extensive tutorials, and examples make it easy to learn how to use Excel for analyzing data. A downloadable StatPlus add-in for Microsoft Excel, data sets for exercises, and interactive concept tutorials are available on the Book Companion Website.",
        "link":"https://online.fliphtml5.com/fxqlq/qbin/"
    },
    {
        "id":3,
        "name":"Game Engine Architecture",
        "image":"https://previews.dropbox.com/p/thumb/ABoZ03tCJyFuC1TdxJegV4zEWbuL8_2ioOAqluhrso3fgFLUX8AGIU4P7cBHfr9BDgWR4voZk8XFu3lnFF9Z_u8Hp-o7HTlV5TK9KXckr0Z-OPWaVqofACke_iVWCQqCs8aGh3717BoUzAJIlcjyzdVblVEsoDuBiFExJmAqKl3lFxojNfpzEJdk5HSHcR0FqAa2s3h37906qRtVbuNCa3_GWZram3E9Xe1M_6T3fVkcvWoIxBnpNZPE18LKC62NxyoFUNo5SGz56xgKb04DqYrIsWhWosY3uHtdIsuGCClja7jB0ylFN_bMb27gmpTMUesUfydy3gMwPsPqyV_MK4Rt0BI5OiXTaRTgAiWMuqg6t891fqQaEWcs6pKpkB4OdQw/p.jpeg",
        "des":"Game Engine Architecture covers both the theory and practice of game engine software development, bringing together complete coverage of a wide range of topics. The concepts and techniques described are the actual ones used by real game studios like Electronic Arts and Naughty Dog. The examples are often grounded in specific technologies, but the discussion extends way beyond any particular engine or API. The references and citations provided in this book make it a great jumping off point for those who wish to dig deeper into any particular aspect of the game development process.",
        "link":"https://online.fliphtml5.com/fxqlq/epbu/"
    },
    {
        "id":4,
        "name":"HTML5 and CSS3 2nd Edition: Level Up with Today’s Web Technologies",
        "image":"https://previews.dropbox.com/p/thumb/ABpjurJetTKIu3-R8g6xpWO8Gq2NOp8detVaNFdUiDQnDBXA7VRWn8HwF7I4IGVUNVR7Ej_cRZBXnk117U2_VCYNvBtk0_JnpIoa4o4JDMATmfOrmkAX4jZLDm1mr7t50EdBGtR6Lf_l4a6vDuZPAcdRZNF56qjl_uJnoMbX4xcIAaNcxGQ8r9h6-F7jF-dFfBBawhPI2b9y9OOEpkgUwSQveyGtgq0NdTPeqJDI6jYzsS_yixfz78xGRmux88IanjFdIrHkGRjq8k04N8xchxeFP-NI_FeS-IK3hq068hvsSpu8Kga7ihBG_DiGyqKiaaIBklE1_fXEPKqLETVn5EbZzUVvX6huCG0YXbBtgwOEUowQEw-RkenLqbwesrRB-4I/p.jpeg",
        "des":"This revised second edition walks you through new features such as IndexedDB, CSS Animations, SVG, and more, along with updated fallback solutions. You'll use HTML5's new markup to create better structure for your content and better interfaces for your forms. You'll work with new form controls and validations, and build interfaces that are accessible to assistive technology and mobile devices. You'll draw with the Canvas and SVG, do simple animations with pure CSS, work with advanced CSS selectors, and make audio and video play natively.You'll bring your web apps to the next level as you use Web Storage and IndexedDB to save data on the client and make applications available offline. And you'll discover how to use web sockets, geolocation, cross-document messaging, and the History API to create even more interactive applications.Today, you have the flexibility that used to be only available through large JavaScript libraries or proprietary plugins. Get ready for today's web.",
        "link":"https://online.fliphtml5.com/fxqlq/vkgq/"
    },
    {
        "id":5,
        "name":"Internet of Things",
        "image":"https://previews.dropbox.com/p/thumb/ABpVIxQE8uP3TiS1nXI4idMj1JNk-5jif_Jvp17XjsLT6TfipXnQS_Rxkm9KgrpTaVb5wIoHhCzBPWzRQOyz1vH3gHh-QMqf8nuIDfMGTt2fnK0gllF7QeVt7q1lHm0Lb23B-3OB_NxHSH8gCadTNVZF4sSRQtwUWzuGNhZk8N0hcoCyP6BXj_fcZBYGBQMhU9-OrYOIOaJa7RsgpDGNdo9pV9qIXzu9L4DeJDeet9GUk6A-l7KX3NBtvKpRlWF6ztuokNZNxIV8EbQzTWEf7FzeJ15vIfOWFrB_VPwPKnNNNhWM0hAl2-ItJyMWhSWuPBbuU_CmeAB44i_0KHSAx0VTyvIvVDh3mKxK1nVA3U02TszembCh13Mtlq-Jk2GN3WM/p.jpeg",
        "des":"As more and more devices become interconnected through the Internet of Things (IoT), there is an even greater need for this book,which explains the technology, the internetworking, and applications that are making IoT an everyday reality.The book begins with a discussion of IoT ecosystems and the technology that enables them, which includes:Wireless,Infrastructure and Service Discovery,rotocols,Integration Technologies and Tools,Application and Analytics Enablement Platforms.A chapter on next-generation cloud infrastructure explains hosting IoT platforms and applications. A chapter on data analytics throws light on IoT data collection, storage, translation, real-time processing, mining, and analysis, all of which can yield actionable insights from the data collected by IoT applications. There is also a chapter on edge/fog computing.",
        "link":"https://online.fliphtml5.com/fxqlq/ahhl/"
    },
    {
        "id":6,
        "name":"Internet Traffic Engineering",
        "image":"https://previews.dropbox.com/p/thumb/ABqBiPfRxTD8tzCivyOp0MlbNZOlA0meTgL7ai0TMVCF0vB5oxnORVUdWngyJaPjwamdF9Iauf7fFAW4RrGWtOvgpi5oWh9OmUI7spG1dlJAfE8Vw-pZ3SFRrQyszNkNswe2OjUuLftW-xI4G4c9dHJviVwlVg44wu-IpLUkUPPCpRHMG7AIdzZ1HWxejBbauzsBynySt3LNt2-pmOhHzLIwAXDXxotjoU2MN0z7sxLxj8TqLPk3CJ-nYF_Mz-SKzsDRuYFpGIWzKhtq7dizfvwae27ONOAH6qK524nj_H4S4i0lcBWMrwOgm_vXOekQTLcrWLOly98xN11GzsL15oIN1LJ6sISGpE9VG7c769WhOS67IvED7KkgaHXy324FbPo/p.jpeg",
        "des":"Due to concerns about resilience and performance, more and more stub networks in the Internet rely on multi-homing. Multi-homing consists in connecting a network to the Internet at different access points. As traffic leaves and enters the network through several access links, multi-homed networks need to control their traffic, also called traffic engineering. Multi-homed networks typically perform traffic engineering by tweaking the BGP routing protocol. The purpose of BGP is to distribute the information about reachable networks across the whole Internet, not to perform traffic engineering. It is thus important for multi-homed networks to know the complexity of traffic engineering with BGP. In this book, we explain how BGP can be used to engineer the traffic and what can be expected from doing it. The content of this book targets two types of readers. First, the network managers of small to medium-size stub networks will better understand BGP and how to use it to engineer their traffic. Second, researchers in networking will learn about three different research areas: Internet traffic characteristics, interdomain routing, and evolutionary optimization.",
        "link":"https://online.fliphtml5.com/fxqlq/wgsn/"
    },
    {
        "id":7,
        "name":"iOS App Reverse Engineering",
        "image":"https://previews.dropbox.com/p/thumb/ABrzTTDnziEyeag_nvnmZKHdyW1VaMIbYTQcyGXWs_eJpJAT9x1jcxygUon09GHkt_AOnBFjoY_8apEf7hu4wM_ADzxrqBOpxVlY1P2nFhKK2ZX_a28f-HJz4aLTO7T_MiNeLN6QxGxFyPHzsClaM9gqvB1EQF6Q1MoCS0hJhC3FfGTJXRob0_fVarmWqbARfbapkO1EoWRFLrYVbNa22IkzksRSMLKlsTYWtL53du7dC4w2WhcUJYByae5H8097E2883BPqVw4Zse7IxP7iaaAP5bdgJcpXLOenJwy5GTmE1FyC92j5TDJjDzsbEmWfavFEkx8oOJRcI2hhTCot_oD6MOnSyUZ6eUB26DSVlMXhRPtUW87zYk_bgfTvGvw6tXI/p.jpeg",
        "des":"Reverse engineering is the direct opposite of building or engineering an application: you break things down bit by bit to see how they actually work. Developers incorporate reverse engineering techniques to solve tasks from investigating bugs in code to ensuring smooth and easy legacy code maintenance.When reverse engineering software, the operating system it was created for should be one of the first things you pay attention to. In this article, we describe the basic concepts of reverse engineering macOS software and iOS apps. This tutorial will be useful for developers who want to know more about macOS and iOS reverse engineering.",
        "link":"https://online.fliphtml5.com/fxqlq/ijnf/"
    },
    {
        "id":8,
        "name":"Practical MATLAB Applications for Engineers",
        "image":"https://previews.dropbox.com/p/thumb/ABq83S0sd4vSf0CiYHdAXb0nH9xqnAufyuAVgm5pv2X2Kgd-_saetC-wE_HevjGLJPpk76HSRpQkaZjJFFqzGL-EkVj8iWPE4sFgxX3_b6JXmE9NKjK3NRvganMISvIsvtzYjLu3KgFgC8Xs-IvA87_gl-OM_2nKlyTl-xBd63zEoG8oT6G8OlJA7efKQ0041wNLme2E0wLdkjqe9mTZbB9Hm4Xa8J47w26Dsk78F6-XI1ZADR9_V00BhLhKkCi3oHJlk5KUcMFhkeuu_q66Dg1cLQtg9fmhWVE0Xt7TrgVwUFmXaHtXveraOPgKAqtiVEebLznv4MshySUYMekylPqlIpkspnMmYCU3kNfrhNuUgtNnoJQBy0eWavcfVHvfY38/p.jpeg",
        "des":"Practical Matlab Applications for Engineers provides a tutorial for those with a basic understanding of Matlab®. It can be used to follow Misza Kalechman’s, Practical Matlab Basics for Engineers (cat no. 47744). This volume explores the concepts and Matlab tools used in the solution of advanced course work for engineering and technology students. It covers the material encountered in the typical engineering and technology programs at most colleges. It illustrates the direct connection between theory and real applications. Each chapter reviews basic concepts and then explores those concepts with a number of worked out examples.",
        "link":"https://online.fliphtml5.com/fxqlq/heef/"
    },
    {
        "id":9,
        "name":"Social Media Marketing: The Next Generation of Business Engagement",
        "image":"https://previews.dropbox.com/p/thumb/ABoF02vViOG9P5MHKGv7vevo0ark2VqzdE-ZQGvMMtV3-4PTSBJN3Uej5MOeg5ZbcA3J_JxZwdxl_zM2WO13YJ_snhnha1WB1k39de4-0vK-LiKjn4Wd3onpKAXPKQnjNVJFudLyeB1K6b5bUoDezbCAJ-gogtZCB112B0Z44xMNG-tMIFQt4i6RjoGHsvGgHVLyhFXEXs6vxyMvSUTFcXDsK9BpXv3CvyGkOhRJENAx6-oXg4fU0C9QoN3C8wFKlhQuZFg_fEUTWeLSCmsvLmN_NRaeBf-TKmxkZ5XdRyM_o1P7JLcw5vDsR_gRJBOVeyKue-qEnwpuQVhXMnZtAxoHaMElhh8phirXUcQUcXCAeN98kSlgzJKInD6__Fpo25M/p.jpeg",
        "des":"The road to social media marketing is now well paved: A July 2009 Anderson Analytics study found 60 percent of the Internet population uses social networks and social media sites such as Facebook, My Space and Twitter. Collaboration and innovation, driven by social technology, are what's next. Written by the author of the bestselling Social Media Marketing: An Hour a Day in collaboration with Jake McKee, Social Media Marketing: The Next Generation of Business Engagement takes marketers, product managers, small business owners, senior executives and organizational leaders on to the next step in social technology and its application in business. In particular, this book explains how to successfully implement a variety tools, how to ensure higher levels of customer engagement and how to build on the lessons learned and information gleaned from first-generation social media marketing efforts and to carry this across your organization.",
        "link":"https://online.fliphtml5.com/fxqlq/yokh/"
    },
    {
        "id":10,
        "name":"Tutorials: Animation - Autodesk | 3ds Max Design, Engineering",
        "image":"https://previews.dropbox.com/p/thumb/ABorSAGCMMHsKifGXSf_QnWE6cUEhZyotLsEOHnrgLaqxwohdSrYcge4UAh0dH_hnQLRGxGdkOrvF1ZteHdF_27-wVy-BlXYdGfN2xkVe-dAPJURPorKkkUMWyrNQ2V-BfKmYyzw1WHC71N5gmljBwnPE_r3Tjd7qn18z-e2akQGB_nlm6uAn3StCYyV8DTGK7d5TolpBD8tyJdooi8SITHFBO7bU8X7txZbjwKMwoh5H4f4nZyFTE8kPyAUxf6C1wyUGAiLcwnYgAN0ZDo1lsFqtJ_E6pB_qTXPJniZ2WX0E9ZC25JQjQN0QnHBTz0YJMr2pQcCY3QOmv0B3nX4-n7ckQHbJ8XQukHtYZrikl_DflF6nWd7IZAE9kjRcB16ycY/p.jpeg",
        "des":"The following are registered trademarks or trademarks of Autodesk, Inc., in the USA and other countries: 3DEC (design/logo), 3December, 3December.com, 3ds Max, ADI, Alias, Alias (swirl design/logo), AliasStudio, AliasWavefront (design/logo), ATC, AUGI, AutoCAD, AutoCAD Learning Assistance, AutoCAD LT, AutoCAD Simulator, AutoCAD SQL Extension, AutoCAD SQL Interface, Autodesk, Autodesk Envision, Autodesk Insight, Autodesk Intent, Autodesk Inventor, Autodesk Map, Autodesk MapGuide, Autodesk Streamline, AutoLISP, AutoSnap, AutoSketch, AutoTrack, Backdraft, Built with ObjectARX (logo), Burn, Buzzsaw, CAiCE, Can You Imagine, Character Studio, Cinestream, Civil 3D, Cleaner, Cleaner Central, ClearScale, Colour Warper, Combustion, Communication Specification, Constructware, Content Explorer, Create>what's>Next> (design/logo), Dancing Baby (image), DesignCenter, Design Doctor, Designer's Toolkit, DesignKids, DesignProf, DesignServer, DesignStudio, DesignStudio (design/logo), Design Web Format, Discreet, DWF, DWG, DWG (logo), DWG Extreme, DWG TrueConvert, DWG TrueView, DXF, Ecotect, Exposure, Extending the Design Team, Face Robot, FBX, Filmbox, Fire, Flame, Flint, FMDesktop, Freewheel, Frost, GDX Driver, Gmax, Green Building Studio, Heads-up Design, Heidi, HumanIK, IDEA Server, i-drop, ImageModeler, iMOUT, Incinerator, Inferno, Inventor, Inventor LT, Kaydara, Kaydara (design/logo), Kynapse, Kynogon, LandXplorer, LocationLogic, Lustre, Matchmover, Maya, Mechanical Desktop, Moonbox, MotionBuilder, Movimento, Mudbox, NavisWorks, ObjectARX, ObjectDBX, Open Reality, Opticore, Opticore Opus, PolarSnap, PortfolioWall, Powered with Autodesk Technology, Productstream, ProjectPoint, ProMaterials, RasterDWG, Reactor, RealDWG, Real-time Roto, REALVIZ, Recognize, Render Queue, Retimer,Reveal, Revit, Showcase, ShowMotion, SketchBook, Smoke, Softimage, SoftimageXSI (design/logo), SteeringWheels, Stitcher, Stone, StudioTools, Topobase, Toxik, TrustedDWG, ViewCube, Visual, Visual Construction, Visual Drainage, Visual Landscape, Visual Survey, Visual Toolbox, Visual LISP, Voice Reality, Volo, Vtour, Wire, Wiretap, WiretapCentral, XSI, and XSI (design/logo)",
        "link":"https://online.fliphtml5.com/fxqlq/cvzb/"
    },
]
export default Technology;